# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

vector = np.zeros((100), dtype=np.int64)
print(vector)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
vector = np.ones((100), dtype=np.int64)
print(vector)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
vector = np.full((100), 3)
print(vector)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [6]:
np.info(np.add)
? np.add

#### 5. Поменять 2 строки в матрице

In [11]:
matrix = np.diag([1,2,3,4,5,6,7,8,9])

i, j = 2, 6
matrix[[i,j]]= matrix[[j,i]]
print(matrix)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


#### 6. Создать вектор со значениями от 10 до 100

In [12]:
vector = np.arange(10, 100)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 7. Развернуть вектор (первый становится последним)

In [13]:
vector = np.arange(10, 100)
vector = vector[::-1]
print(vector)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [14]:
matrix = np.arange(16).reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [16]:
vector = np.arange(1,6)
n=len(vector)-1

for i in range(n):
    vector = np.insert(vector,n*(i)+1,(0,0,0))
print(vector)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 10. Создать 3x3 единичную матрицу

In [17]:
matrix = np.diag(np.full(3,1))
print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [18]:
data = np.random.random((3,3,3))
print(data)

[[[0.30703773 0.51653037 0.00414177]
  [0.93776604 0.22653374 0.77390086]
  [0.02551469 0.84887299 0.30445078]]

 [[0.39840106 0.76881909 0.57521938]
  [0.09417703 0.08816128 0.53106242]
  [0.15080665 0.6175688  0.71233534]]

 [[0.64199366 0.39019011 0.31052603]
  [0.07071301 0.96505045 0.08636662]
  [0.84046938 0.45171477 0.31557258]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [23]:
np.random.seed(5)
data = np.random.randint(-100,100,(10,10))
#print(data)
print(np.min(data))
print(np.max(data))

-100
93


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
vector = np.random.randint(1,1000,30)
#print(vector)
print(vector.mean())

452.6


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [34]:
a = np.ones((10,10),dtype=int)
a[1:-1,1:-1] = 0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [40]:
def f(i, j):
  return (i ** j) % (i + j + 1)

a = np.fromfunction(f, (8,8), dtype=int)
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  2,  4,  2,  2,  0,  1,  8],
       [ 1,  3,  3,  6,  1,  0,  9,  9],
       [ 1,  4,  2,  0,  4,  4,  4,  4],
       [ 1,  5,  1,  8,  5,  1,  1,  8],
       [ 1,  6,  0,  6,  9,  0, 12,  6],
       [ 1,  7,  9,  2,  1, 11,  7, 13]])

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [41]:
matrix = np.diag([1,2,2,4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [42]:
def f1(i,j):
  return (i+j)%2

a = np.fromfunction(f1, (8,8), dtype=np.int16)
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [43]:
I, J, K = 6, 7, 8
data = np.full((I,J,K),1)

stop = 100
for i in range(I):
  for j in range(J):
    for k in range(K):
      if i*(J*K) + j*(K) + k == stop:
        print(i, j, k)
        break

print(np.unravel_index(100, (6,7,8)))

1 5 4
(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [45]:
matrix = np.array([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]])
matrix = np.tile(matrix, (4,1))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [46]:
a = np.array([[0,1,2],
              [1,0,3],
              [-1,2,1],
              [0,0,0],
              [1,0,1]])
b = np.array([[1,2],
              [2,1],
              [0,0]])
print(a@b)

[[2 1]
 [1 2]
 [3 0]
 [0 0]
 [1 2]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [47]:
np.random.seed(10)
a = np.random.randint(1, 10, 20)
a[a < 8] *= -1
a[abs(a) <= 3] *= -1
print(a)

[-5  1  2  1  2  9  1  9 -7 -5 -4  1 -5 -7  9  2  9 -5  2 -4]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [48]:
def f1(i,j):
  return j

a = np.fromfunction(f1, (5,5), dtype=np.int64)
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 24. Есть генератор, сделать с его помощью массив

In [49]:
a = np.array([2**i+1 for i in range(5)])
print(a)

[ 2  3  5  9 17]


#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [50]:
a = np.linspace(0.1,1,10,endpoint=False)
print(a)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


#### 26. Отсортировать вектор

In [53]:
a = np.random.randint(0,50,20)
a.sort()
print(a)

[ 6 11 12 13 15 15 15 21 22 24 28 32 40 42 42 43 44 45 48 49]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [56]:
a = np.array([1,2,3,5,4,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.array_equal(a,b))

False


#### 28. Сделать массив неизменяемым

In [57]:
array = np.zeros(10)
array.flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [ ]:
n = 3
l = 50
a = np.random.randint(1,50,l)
a.sort()
print(a[l-n:])

[47 47 49]


#### 30. Заменить максимальный элемент на ноль

In [59]:
a = np.random.randint(1,50,10)
print(a)
a[a.argmax()] = 0
print(a)

[30 17 21 19 49 15 16 18 26 47]
[30 17 21 19  0 15 16 18 26 47]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [61]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [62]:
X = np.random.randint(1,10,5)
Y = np.random.randint(10,20,5)
print(X)
print(Y)
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[1 2 1 2 1]
[19 12 11 11 10]
[[-0.05555556 -0.09090909 -0.1        -0.1        -0.11111111]
 [-0.05882353 -0.1        -0.11111111 -0.11111111 -0.125     ]
 [-0.05555556 -0.09090909 -0.1        -0.1        -0.11111111]
 [-0.05882353 -0.1        -0.11111111 -0.11111111 -0.125     ]
 [-0.05555556 -0.09090909 -0.1        -0.1        -0.11111111]]


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
  print(dtype)
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
  print(dtype)
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)

<class 'numpy.int8'>
-128
127
<class 'numpy.int32'>
-2147483648
2147483647
<class 'numpy.int64'>
-9223372036854775808
9223372036854775807
<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [66]:
a = np.array([1,2,3,4,5,6,7,8,9])
for i in a:
  print(i, end = " ")
print()
print(*a)

1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9


#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [67]:
array = np.arange(100)
print(array)
a = np.random.uniform(0,100)
print(a)
index = (np.abs(array-a)).argmin()
print(array[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
13.456300346431615
13


#### 36. Преобразовать массив из float в int

In [68]:
array = np.arange(10, dtype=np.int32)
print(array)
array = array.astype(np.float32, copy=False)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [70]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array):
  print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [71]:
n = 10
p = 10
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False), 10)
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 10.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10.  0.  0.  0.  0.  0.  0.  0. 10. 10.]
 [ 0.  0.  0.  0.  0.  0. 10.  0. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0. 10. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [ ]:
a = np.arange(16).reshape(4,4)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
a = np.random.randint(0,10,(4,5))
n = 1
print(a)
print(a[a[:,n].argsort()])

[[6 1 8 0 9]
 [0 6 4 3 4]
 [5 0 1 2 0]
 [9 8 9 6 3]]
[[5 0 1 2 0]
 [6 1 8 0 9]
 [0 6 4 3 4]
 [9 8 9 6 3]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [78]:
a = np.random.randint(0,2,(4,20))
print(a)
print((~a.any(axis=0)).any())

[[0 1 1 1 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0]
 [1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 1 0]
 [1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 1 1 0]
 [0 0 1 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1 0]]
True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [79]:
a = np.ones(10)
f = np.random.randint(0,len(a),20)
print(a)
print(f)
a += np.bincount(f, minlength=len(a))
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 9 2 5 0 7 2 6 5 7 3 7 0 3 6 0 7 2 9 5]
[4. 1. 4. 4. 1. 4. 3. 5. 1. 3.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [80]:
w,h = 64,64
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [81]:
a = np.random.randint(1,10,(5,6,7,8))
#print(a)
s = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(s)

[[293 261 269 303 271 283]
 [252 290 290 294 259 285]
 [290 274 277 284 267 262]
 [272 269 308 271 276 267]
 [250 293 270 286 269 290]]
